---
docker:
  host: "https://127.0.0.1:2376"
  read_timeout: 300

stacks:
  -
    name: debian_jessie
    units:
      -
        name: debian
        docker_image: debian
        pre_build_scripts:
          - ./pre_build_script2.sh
        ports:
          - '9999:9999'
        volumes:
          - '/outside/container/path:/inside/container/path'
