---
docker:
  host: "https://127.0.0.1:2376"
  read_timeout: 300

stacks:
  - name: debian_jessie
    units:
      - name: needed_debian
        version: 1.1.0
        dockerfile: ./Dockerfile
        pre_build_scripts:
          - ./pre_build_script1.sh
        ports:
          - '8888:8888'
        volumes:
          - '/outside/container/path:/inside/container/path'

      - name: debian
        version: 1.0.0
        dockerfile: ./Dockerfile
        pre_build_scripts:
          - ./pre_build_script2.sh
        ports:
          - '9999:9999'
        volumes:
          - '/outside/container/path:/inside/container/path'
        needed_unit_names:
          - needed_debian

      - name: debian_external
        version: 1.0.0
        docker_image: debian:jessie

      - name: debian_pseudo
        version: 1.0.0
        instances: 2
        dockerfile: ./Dockerfile
