---
docker:
  host: "https://127.0.0.1:2376"
  read_timeout: 300

stacks:
  -
    name: debian_jessie
    units:
      -
        name: debian
        version: abc
        dockerfile: ./Dockerfile
        ports:
          - '9999:9999'
        volumes:
          - '/outside/container/path:/inside/container/path'
        dependant_unit_names:
          - dependant_debian
