language: ruby
before_install: gem install bundler --version 1.9.7
rvm:
  - 2.0
  - 2.1
  - 2.2
branches:
  only:
    - master
    - wip
script:
  - bundle exec rake test:style
  - bundle exec rake spec:unit
