---
docker:
  host: "https://127.0.0.1:2376"
  read_timeout: 300

stacks:
  -
    name: debian_jessie
    containers:
      -
        name: debian
        version: 1.0.0
        ports:
          - '9999:9999'
        volumes:
          - '/outside/container/path:/inside/container/path'
        dependant_container_names:
          - dependant_debian
