---
stacks:
  - name: percheron-test
    units:
      - name: base
        version: 9.9.9
        dockerfile: ./Dockerfile.base
        startable: false

      - name: app1
        version: 9.9.9
        dockerfile: ./Dockerfile.app1
        needed_unit_names:
          - base

      - name: app2
        version: 9.9.9
        dockerfile: ./Dockerfile.app1
        needed_unit_names:
          - base
        ports:
          - 12349:12349

      - name: app3
        version: 9.9.9
        docker_image: busybox:ubuntu-14.04
        start_args: [ 'sh', '-c', "while true; do date ; echo 'hello from percheron'; done" ]
